typescript: true

commandDir: bin/semo/commands
pluginDir: bin/semo/plugins
extendDir: bin/semo/extends
scriptDir: bin/semo/scripts
hookDir: bin/semo/hooks

$plugin:
  semo:
    repl:
      hook: true
      extract:
        - application
