language: node_js
node_js:
  - '8'
script: npm run jsdoc
deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    tags: true
  tag: latest
