typescript: true

commandDir: lib/commands
commandMakeDir: src/commands
extendDir: lib/extends
extendMakeDir: src/extends
hookDir: lib/hooks
hookMakeDir: src/hooks

$core:
  env:
    SEMO_PLUGIN_DIR: ..
